### ISSUE TITLE
npx mudslide not working on Rasberry Pi2 (Bookworm)

### ISSUE THREAD

**Issue by AuroreVgn** [robvanderleek/mudslide#158]
Hello,

I have installed mudslide on my Rasperry Pi2 running Raspbian 12 (Bookworm). It's a brand new installation.

After a successfull QR-Code registration, I have the following issue when I tried to do anything with `npx mudslide` command: 

```
npx mudslide@latest groups
node:internal/modules/cjs/loader:445
      throw err;
      ^

Error: Cannot find module '/home/pi/.npm/_npx/ce95761724e6020f/node_modules/@protobufjs/float/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:437:19)
    at Module._findPath (node:internal/modules/cjs/loader:705:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/pi/.npm/_npx/ce95761724e6020f/node_modules/@whiskeysockets/baileys/node_modules/protobufjs/src/util/minimal.js:14:14)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/pi/.npm/_npx/ce95761724e6020f/node_modules/@protobufjs/float/package.json',
  requestPath: '@protobufjs/float'
}

Node.js v18.19.0
```

```
npx mudslide@latest send _group_id_@g.us 'Hello world'
node:internal/modules/cjs/loader:445
      throw err;
      ^

Error: Cannot find module '/home/pi/.npm/_npx/ce95761724e6020f/node_modules/@protobufjs/float/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:437:19)
    at Module._findPath (node:internal/modules/cjs/loader:705:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/pi/.npm/_npx/ce95761724e6020f/node_modules/@whiskeysockets/baileys/node_modules/protobufjs/src/util/minimal.js:14:14)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/pi/.npm/_npx/ce95761724e6020f/node_modules/@protobufjs/float/package.json',
  requestPath: '@protobufjs/float'
}

Node.js v18.19.0

```

I have searched on Git and I found this [closed issue](https://github.com/robvanderleek/mudslide/issues/125) but I'm not really sure if it's the same problem.

Do you have any idea to solve this problem?

Thanks :-)

**Comment by robvanderleek** [comment]
Hi @AuroreVgn 

Unfortunately, I don't have access to this platform and can't reproduce it on x64 Linux. So, not sure what the root cause is.
Maybe you can try the latest ARM binary? https://github.com/robvanderleek/mudslide/releases/download/0.31.0/mudslide-linuxstatic-arm64

**Comment by eliafino** [comment]
Maybe Pi2 isn't x64

**Comment by AuroreVgn** [comment]
> Maybe Pi2 isn't x64

You're right... Pi2 isn't x64.

Before I re-install this Pi2, it was running Raspbian 11 and `mudslide` worked perfectly.

Is there any 'old version' or arm (for 32 bit) I can use?

**Comment by AuroreVgn** [comment]
> Hi @AuroreVgn
> 
> Unfortunately, I don't have access to this platform and can't reproduce it on x64 Linux. So, not sure what the root cause is. Maybe you can try the latest ARM binary? https://github.com/robvanderleek/mudslide/releases/download/0.31.0/mudslide-linuxstatic-arm64

Thank you for your reply!
I already use the lastest version.

```
npx --version
10.9.2
npx mudslide --version
0.31.0
```

**Comment by AuroreVgn** [comment]
I tried `npx mudslide send _group_id_@g.us 'Hello world'` without `@lastest` and it works....

**Comment by AuroreVgn** [comment]
I tried npx mudslide send _group_id_@g.us 'Hello world' without @lastest and it works....
