### ISSUE TITLE
Cannot Send Messages Anymore, Connection Error

### ISSUE THREAD

**Issue by AzlanCoding** [robvanderleek/mudslide#48]
Hello, I'm working on an app to automatically send WhatsApp messages to groups, this was previously working on replit.com, however, it has for some reason stopped working suddenly. This is what i tried in the command line:

<br>
<br>
<br>
```
~/DopeyWorrisomeDatasets$ node ./node_modules/mudslide/dist/index.js send me "HELLOO" -v
{"level":30,"time":1686561186581,"pid":565,"hostname":"180d1982ff8e","browser":["Linux","Chrome","10.15.0"],"helloMsg":{"clientHello":{"ephemeral":"MgbVX67Km0S4rIVw5Zts8TZ0VXToSS0QE9R+9aTFqQg="}},"msg":"connected to WA Web"}
{"level":30,"time":1686561186686,"pid":565,"hostname":"180d1982ff8e","node":{"username":"6591380435","passive":true,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2243,"tertiary":7},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","device":58},"msg":"logging in..."}
{"level":30,"time":1686561189837,"pid":565,"hostname":"180d1982ff8e","trace":"Error: Connection Failure\n    at WebSocket.<anonymous> (/home/runner/DopeyWorrisomeDatasets/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:429:13)\n    at WebSocket.emit (node:events:513:28)\n    at WebSocket.emit (node:domain:489:12)\n    at /home/runner/DopeyWorrisomeDatasets/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35\n    at Object.decodeFrame (/home/runner/DopeyWorrisomeDatasets/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/home/runner/DopeyWorrisomeDatasets/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15)\n    at WebSocket.emit (node:events:513:28)\n    at WebSocket.emit (node:domain:489:12)\n    at Receiver.receiverOnMessage (/home/runner/DopeyWorrisomeDatasets/node_modules/ws/lib/websocket.js:1184:20)\n    at Receiver.emit (node:events:513:28)","msg":"connection errored"}
```

<br>
<br>
<br>
Am I the only one with this problem? How can I fix it?

**Comment by WolfRamiO74** [comment]
same issue here i cant login even if i clear cache dir... using the Linux BIN on Debian 11 (not the NPM version)

**Comment by AzlanCoding** [comment]
Some temporary solutions may be found here:
https://github.com/WhiskeySockets/Baileys/issues/130
Hopefully it will be resolved soon

**Comment by WolfRamiO74** [comment]
i update to the last version, clear the cache folder and now its working... some commands also change.
