### ISSUE TITLE
error after update 

### ISSUE THREAD

**Issue by JR9842210171** [robvanderleek/mudslide#67]
Hi,

it shows error after update 

C:\Users\Lenovo\AppData\Local\npm-cache\_npx\ce95761724e6020f\node_modules\mudslide\dist\commands.js:27
                const buttons = options.button.map((b, idx) => ({
                                               ^

TypeError: Cannot read properties of undefined (reading 'map')
    at C:\Users\Lenovo\AppData\Local\npm-cache\_npx\ce95761724e6020f\node_modules\mudslide\dist\commands.js:27:48
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Lenovo\AppData\Local\npm-cache\_npx\ce95761724e6020f\node_modules\mudslide\dist\commands.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0

**Comment by robvanderleek** [comment]
It's fixed in 0.22.2.

Thanks for reporting @JR9842210171 !
