### ISSUE TITLE
TypeError: process.stdin.setRawMode is not a function on docker on Synology NAS

### ISSUE THREAD

**Issue by zheffie** [robvanderleek/mudslide#78]
Hi there,

I'm using docker  on a Synology NAS
After `login` command and scanning the QR code, the output yields:

```
✔  success   Logged in
◼  pause     Wait until WhatsApp finishes connecting, then press any key to exit
/usr/local/lib/node_modules/mudslide/dist/whatsapp.js:136
        process.stdin.setRawMode(true);
                      ^

TypeError: process.stdin.setRawMode is not a function
    at /usr/local/lib/node_modules/mudslide/dist/whatsapp.js:136:23
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/mudslide/dist/whatsapp.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/mudslide/dist/whatsapp.js:27:12)
    at waitForKey (/usr/local/lib/node_modules/mudslide/dist/whatsapp.js:134:12)
    at /usr/local/lib/node_modules/mudslide/dist/whatsapp.js:161:27
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/mudslide/dist/whatsapp.js:31:71
    at new Promise (<anonymous>)

Node.js v20.11.0

```

after that, the `cache` folder seems to be populated, and Whatsapp application properly shows a linked device.
However subsequent commands again always trigger the generation of QR code and ultimately do not execute.

Any idea on what could be te problem?

**Comment by robvanderleek** [comment]
Hi @zheffie 

Great you managed to resolve this issue yourself.
I've updated the README so other users won't bump into the same problem.

Thanks, Rob
